base_url = "https://eldhrimnir.valeriodelbello.net"
title = "Eldhrimnir"
description = "I put my creations here when I have nowhere to put them."
theme = "abridge"

default_language = "en"
compile_sass = true
minify_html = false
build_search_index = false
generate_feed = false
taxonomies = []


[markdown]

highlight_code = true
highlight_theme = "css"
render_emoji = false
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false


[extra]

menu = [
    {url = "blog", name = "Blog", slash = true, blank = false, size="s90"},
    {url = "notes", name = "Notes", slash = true, blank = false, size="s90"},
    {url = "archive", name = "Archive", slash = true, blank = false, size="s90"},
]

toc = true
recent = true
recent_items = 15
series = true
series_items = 9

meta_index = { position="top", size="s90", author=false, readtime=true, readstring="min", date=true, updated=true, categories_tags=false, divider="&bull;" }
meta_post = { position="top", size="s90", author=false, readtime=true, readstring="min", date=true, updated=true, categories_tags=false, divider="&bull;" }

hide_section_dates = false
hide_page_nextprev_titles = true
title_size_index = "s90"
footer_size = "s90"
footer_credit = true

textlogo = 'Delby Eldhrimnir'

sitedesc = true
headhr = true
foothr = true

copyright = false

title_separator = "|"

author = "Valerio Del Bello"
keywords = "Delby, Eldhrimnir, blog, notes, Valerio, Del, Bello, Delby Eldhrimnir, Valerio Del Bello"

seo = true

online_url = "https://eldhrimnir.valeriodelbello.net"
online_indexformat = "elasticlunr_json"
offline = false

uglyurls = false
integrity = true
js_bundle = true

js_copycode = true
js_email_encode = true
js_prestyle = true
js_switcher = true
js_switcher_default = "dark"

search_library = 'elasticlunr'
stylesheets = ["abridge.css"]

pwa = false

icon_search = "svgs search"
icon_adjust = "svgs adjust"
icon_first = "svgs svgh angll"
icon_prev = "svgs svgh angl"
icon_next = "svgs svgh angr"
icon_last = "svgs svgh angrr"
icon_top = "svgs svgh angu"

icon_read = "svgs fa-solid fa-glasses"
icon_date = "svgs fa-solid fa-calendar"
icon_info = "svgs fa-solid fa-circle-info"
icon_author = "svgs fa-solid fa-pen-fancy"

fontawesome = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/all.min.css"
